import { Quest } from "./stores/useQuestStore";

export const quests: Quest[] = [
  // Starter quests
  {
    id: "energy-1",
    title: "First Sunlight",
    description: "Collect 50 energy from sunlight",
    type: "energy",
    target: 50,
    progress: 0,
    reward: 25,
    completed: false,
    claimed: false,
  },
  {
    id: "upgrade-1",
    title: "Growing Beginnings",
    description: "Purchase your first upgrade",
    type: "upgrade",
    target: 1,
    progress: 0,
    reward: 50,
    completed: false,
    claimed: false,
  },
  
  // Intermediate quests
  {
    id: "energy-2",
    title: "Photosynthesis Expert",
    description: "Collect 500 energy from sunlight",
    type: "energy",
    target: 500,
    progress: 0,
    reward: 100,
    completed: false,
    claimed: false,
  },
  {
    id: "stage-1",
    title: "First Evolution",
    description: "Evolve your plant to the second stage",
    type: "stage",
    target: 1,
    progress: 0,
    reward: 200,
    completed: false,
    claimed: false,
  },
  {
    id: "upgrade-2",
    title: "Balanced Growth",
    description: "Purchase 5 total upgrades",
    type: "upgrade",
    target: 5,
    progress: 0,
    reward: 300,
    completed: false,
    claimed: false,
  },
  
  // Advanced quests
  {
    id: "energy-3",
    title: "Energy Harvester",
    description: "Collect 5,000 energy from sunlight",
    type: "energy",
    target: 5000,
    progress: 0,
    reward: 500,
    completed: false,
    claimed: false,
  },
  {
    id: "stage-2",
    title: "Beautiful Bloom",
    description: "Evolve your plant to the third stage",
    type: "stage",
    target: 2,
    progress: 0,
    reward: 750,
    completed: false,
    claimed: false,
  },
  {
    id: "upgrade-3",
    title: "Upgrade Master",
    description: "Purchase 10 total upgrades",
    type: "upgrade",
    target: 10,
    progress: 0,
    reward: 1000,
    completed: false,
    claimed: false,
  },
  
  // Expert quests
  {
    id: "energy-4",
    title: "Solar Powerhouse",
    description: "Collect 50,000 energy from sunlight",
    type: "energy",
    target: 50000,
    progress: 0,
    reward: 5000,
    completed: false,
    claimed: false,
  },
  {
    id: "stage-3",
    title: "Magnificent Growth",
    description: "Evolve your plant to the fourth stage",
    type: "stage",
    target: 3,
    progress: 0,
    reward: 10000,
    completed: false,
    claimed: false,
  },
  {
    id: "upgrade-4",
    title: "Plant Perfection",
    description: "Purchase 20 total upgrades",
    type: "upgrade",
    target: 20,
    progress: 0,
    reward: 25000,
    completed: false,
    claimed: false,
  },
  
  // Endgame quests
  {
    id: "energy-5",
    title: "Solar God",
    description: "Collect 1,000,000 energy from sunlight",
    type: "energy",
    target: 1000000,
    progress: 0,
    reward: 100000,
    completed: false,
    claimed: false,
  },
  {
    id: "stage-4",
    title: "Ultimate Evolution",
    description: "Evolve your plant to the final stage",
    type: "stage",
    target: 4,
    progress: 0,
    reward: 200000,
    completed: false,
    claimed: false,
  },
  {
    id: "upgrade-5",
    title: "Plant Mastery",
    description: "Max out all upgrade paths",
    type: "upgrade",
    target: 45,
    progress: 0,
    reward: 500000,
    completed: false,
    claimed: false,
  },
];
